services:

  pb_backend:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - PB_VERSION=0.28.2
    container_name: pb_backend
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data 
      - ./pb_hooks.js:/pb/pb_hooks.js
    networks:
      - web1
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate --url http://pb_backend:8080
    networks:
      - web1
    restart: unless-stopped

networks:
  web1:
    name: web1
