services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - web1
    restart: unless-stopped
    depends_on:
      - pb_backend

  pb_backend:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - PB_VERSION=0.28.2
    container_name: pb_backend
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data
    networks:
      - web1
    restart: unless-stopped

networks:
  web1:
    name: web1
