services:
  traefik:
    image: "traefik:v2.11"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${DB_ADMIN_USER}" # Make sure this is a valid email for Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Traefik Dashboard
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web1
    restart: unless-stopped

  pb_backend:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        - PB_VERSION=0.28.2
    container_name: pb_backend
    volumes:
      - ./pb_data:/pb/pb_data
      - ./pb_hooks.js:/pb/pb_hooks.js
    networks:
      - web1
    restart: unless-stopped
    environment:
      POCKETBASE_APP_ENV_ADMIN_EMAIL: ${DB_ADMIN_USER}
      POCKETBASE_APP_ENV_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
      POCKETBASE_ENCRYPTION_KEY: ${POCKETBASE_ENCRYPTION_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pb_backend.rule=Host(`pocketbase.johnapps.de`)"
      - "traefik.http.routers.pb_backend.entrypoints=websecure"
      - "traefik.http.routers.pb_backend.tls.certresolver=myresolver"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pb_backend-http.rule=Host(`pocketbase.johnapps.de`)"
      - "traefik.http.routers.pb_backend-http.entrypoints=web"
      - "traefik.http.routers.pb_backend-http.middlewares=https-redirect"
      - "traefik.http.services.pb_backend.loadbalancer.server.port=8080"

networks:
  web1:
    name: web1